#Once the mouse branch is merged into the main ZMK, this file can be rewriting with default code
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mouse-pr-remote
      url-base: https://github.com/ftc
  projects:
    - name: zmk
      remote: mouse-pr-remote
      revision: mouse-ftc
      import: app/west.yml
  self:
    path: config
